//ACTIONS FOR USERS:

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const CLOSE_MODAL = "CLOSE_MODAL";


//ACTIONS FOR COCKTAILS:

export const GET_COCKTAILS_SUCCESS = "GET_COCKTAILS_SUCCESS";
export const GET_COCKTAILS_FAILURE = "GET_COCKTAILS_FAILURE";

export const GET_SINGLE_COCKTAIL_SUCCESS = "GET_SINGLE_COCKTAIL_SUCCESS";
export const GET_SINGLE_COCKTAIL_FAILURE = "GET_SINGLE_COCKTAIL_FAILURE";

export const ADD_COCKTAIL_SUCCESS = "ADD_COCKTAIL_SUCCESS";
export const ADD_COCKTAIL_FAILURE = "ADD_COCKTAIL_FAILURE";

export const GET_USERS_OWN_COCKTAILS_SUCCESS = "GET_USERS_OWN_COCKTAILS_SUCCESS";
export const GET_USERS_OWN_COCKTAILS_FAILURE = "GET_USERS_OWN_COCKTAILS_FAILURE";

//ACTIONS FOR ADMIN:

export const COCKTAIL_TO_PUBLISHED_SUCCESS = "COCKTAIL_TO_PUBLISHED_SUCCESS";
export const COCKTAIL_TO_PUBLISHED_FAILURE = "COCKTAIL_TO_PUBLISHED_FAILURE";

export const DELETE_COCKTAIL_SUCCESS = "DELETE_COCKTAIL_SUCCESS";
export const DELETE_COCKTAIL_FAILURE = "DELETE_COCKTAIL_FAILURE";
